### ISSUE TITLE
Release 1.3.0 Linux binaries… doesn't have any binaries

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [ds160/remarkable-remember#3]
Might make it a bit difficult to use it without compiling it. Haven't checked for the other platforms. [1.2.0](https://github.com/ds160/remarkable-remember/releases/tag/1.2.0) is still working fine.

**Comment by ds160** [comment]
I fixed the problem with uploading build artifacts.

Thanks for reporting the issue.
