### ISSUE TITLE
No such file

### ISSUE THREAD

**Issue by 15ah35** [ds160/remarkable-remember#4]
I get "No such file" error when trying to run Hand Writing Recognition

**Comment by ds160** [comment]
I have modified the code to ignore deleted paged when running Hand Writing Recognition. This should solve your problem.

Can you access the latest build artifacts and test the Hand Writing Recognition, please?
https://github.com/ds160/remarkable-remember/actions/runs/7894671745

Thank you

**Comment by 15ah35** [comment]
Issue is not with deleted pages. Issue with this code:

`String contentFileText = await Task.Run(() => client.ReadAllText(Path.Combine(PATH_NOTEBOOKS, $"{id}.content"))).ConfigureAwait(false);`

The `Path.Combine` function combines the two srings with two forward slashes `//`

eg:

/home/root/.local/share/remarkable/xochitl\\38e089ed-277e-4448-8f84-533cece6beb1.content

That's why file is not being found...

**Comment by ds160** [comment]
I have modified the code. Could you test the Hand Writing Recognition again, please?

**Comment by 15ah35** [comment]
I get this error now after clicking Hand Writing Recognition button. I have already setup the MyScript Application and HMAC keys.
 ![image](https://github.com/ds160/remarkable-remember/assets/17753799/c5abd8cb-3b61-4727-8ef7-24c36b8b4fba)

**Comment by ds160** [comment]
Status code 413 (RequestEntityTooLarge) indicates that the server (MyScript) cannot handle the content of a page. Can you try a different document or split the content of the page in multiple pages, please?
