### ISSUE TITLE
Dark Mode contrast on windows

### ISSUE THREAD

**Issue by ZigPip** [ds160/remarkable-remember#8]
When the "choose your colour" setting on windows is set to dark, the contrast makes text unable to be read. Changing the setting to light produces what is presumably the desired look of the UI.
![image](https://github.com/ds160/remarkable-remember/assets/115329146/3234ceca-47f5-43e1-9a02-dd69fee204d4)
![image](https://github.com/ds160/remarkable-remember/assets/115329146/5a9e0a86-33c1-4055-a5a3-f18a79c9da35)

**Comment by ds160** [comment]
Thanks for reporting. It should be fixed in the latest release (1.5.2)

**Comment by ZigPip** [comment]
Just got around to using it again, it looks wonderful thank you :)
