### ISSUE TITLE
"Connected reMarkable not supported"

### ISSUE THREAD

**Issue by lrgabriel** [ds160/remarkable-remember#9]
Hello!

I'm having trouble connecting to my reMarkable 1 (software 3.14.1.9).  I can login via ssh or the web interface, but not with reMarkable Remember--the error "Connected reMarkable not supported" appears in the status bar.

Is this a firmware version problem, or something else I'm doing wrong?  Happy to help troubleshooting--thanks for your time.

**Comment by ds160** [comment]
You have done nothing wrong. Right now my application is only supporting reMarkable 1.
But I would love to support rM1 as well. If your open to test the application and report problems, I would remove the check for rM1 and you could test. Please let me know. Thank you.

**Comment by lrgabriel** [comment]
Perhaps I made a mistake; I've been calling it a reMarkable 1, but the model number is "RM100".

Either way, I'd be happy to test out whatever you'd like!

**Comment by ds160** [comment]
Please let me know which platform you're using and I will build and upload a special setup that you can use for testing.

**Comment by lrgabriel** [comment]
Win 10 x64, or Fedora 40 x64 (rpm) would be great.  Thank you!

**Comment by ds160** [comment]
I have uploaded a test setup to the latest release - `test-win-x64.zip`.

A logging function has been added to have information when a problem occurs.
The log-file is located here: `C:\Users\<USERNAME>\AppData\Local\ReMarkableRemember\logs.txt`

Please let me know if something fails and attach the log file when a problem occurs.

**Comment by ds160** [comment]
Could you please post the output of `cat /proc/version` when you're connected via SSH?

**Comment by lrgabriel** [comment]
It's going great so far!

Here's `cat /proc/version`:

`Linux version 5.4.70-v1.4.1-rm10x (oe-user@oe-host) (gcc version 11.4.0 (GCC)) #1 Fri May 10 10:33:08 UTC 2024`

**Comment by ds160** [comment]
Thank you for the information and feedback.
Could you please test the hand-writing recognition functionality?
I will create a new release afterwards :)
Thanks for your support

**Comment by ds160** [comment]
New release with rm10x support: 1.6.3
